src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 */
class Product
{

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $img_path;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $create_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $create_who;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $update_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $update_who;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $deleted;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", inversedBy="products",cascade={"persist"})
     */
    private $tags;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getImgPath()
    {
        return $this->img_path;
    }

    public function setImgPath($img_path)
    {
        $this->img_path = $img_path;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreateAt(): ?int
    {
        return $this->create_at;
    }

    public function setCreateAt(?int $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }

    public function getCreateWho(): ?string
    {
        return $this->create_who;
    }

    public function setCreateWho(?string $create_who): self
    {
        $this->create_who = $create_who;

        return $this;
    }

    public function getUpdateAt(): ?int
    {
        return $this->update_at;
    }

    public function setUpdateAt(?int $update_at): self
    {
        $this->update_at = $update_at;

        return $this;
    }

    public function getUpdateWho(): ?string
    {
        return $this->update_who;
    }

    public function setUpdateWho(?string $update_who): self
    {
        $this->update_who = $update_who;

        return $this;
    }

    public function getDeleted(): ?bool
    {
        return $this->deleted;
    }

    public function setDeleted(?bool $deleted): self
    {
        $this->deleted = $deleted;

        return $this;
    }
    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the  update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $image
     */
    public function setImageFile(?File $image = null): void
    {
        $this->imageFile = $image;

        if (null !== $image) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageSize(?int $imageSize): void
    {
        $this->imageSize = $imageSize;
    }

    public function getImageSize(): ?int
    {
        return $this->imageSize;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
        }

        return $this;
    }
}

src/Form/ProductType.php
<?php
/**
 * @author Daniele Agrelli <daniele.agrelli@gmail.com> on 09/05/18 11:36.
 * @copyright Copyright © Daniele Agrelli 2018
 */

namespace App\Form;


use App\Entity\Product;
use App\Entity\Tag;
use Symfony\Bridge\Doctrine\RegistryInterface;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class ProductType extends AbstractType {

    private $doctrine;
    public $tags;

    public function __construct(RegistryInterface $doctrine)
    {
        $this->doctrine = $doctrine;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, ['label' => 'Image'])
            ->add('description', TextareaType::class, ['label' => 'Description','required'=>false])
            ->add('img_path', FileType::class, ['label' => 'Image','required'=>false,'data_class'=>null])
            ->add('tags', CollectionType::class, [
                'label'=>false,
                'entry_type' => TagType::class,
                'allow_add' => true,
                'by_reference' => false,
                'allow_delete' => true,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Entity\Tag;
use App\Form\ProductType;
use App\Form\TagType;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class ProductController extends Controller
{
    /**
     * @Route("/", name="product")
     */
    public function actionIndex()
    {
        return $this->render('product/index.html.twig');
    }

    /**
     * Matches list of /product with page
     *
     * @Route("/product/list/{page}", name="list", requirements={"page"="\d+"})
     */
    public function actionList($page=1)
    {
        $repository = $this->getDoctrine()->getRepository(Product::class);
        $products = $repository->findProductList();
        return $this->render('product/list.html.twig',[
            'products'=>$products
        ]);
    }

    /**
     * Create a new product
     *
     * @Route("/product/create", name="create")
     */
    public function actionCreate(Request $request)
    {
        $product = new Product();
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $product=$form->getData();
            /** @var UploadedFile $file */
            $file = $product->getImgPath();
            if($file = $file ?? null){
                $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

                $file->move(
                    $this->getParameter('image_directory'),
                    $fileName
                );

                $product->setImgPath($fileName);
            }

            $product->setCreateAt(time());

            $originalTags = new ArrayCollection();
            foreach ($originalTags as $tag) {
                if (false === $product->getTags()->contains($tag)) {
                    // remove the Task from the Tag
                    $tag->getTasks()->removeElement($product);

                    $entityManager->persist($tag);
                }
            }

            $entityManager->persist($product);
            $entityManager->flush();


            return $this->redirect($this->generateUrl('product'));
        }

        return $this->render('product/create.html.twig',[
            'form'=>$form->createView(),
        ]);
    }

    /**
     * Update an exist product
     *
     * @Route("/product/{product_id}/edit", name="update",requirements={"product_id"="\d+"})
     */
    public function actionUpdate(Request $request,$product_id)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $product = $this->loadProductEntity($product_id);

        $originalTags = new ArrayCollection();

        // Create an ArrayCollection of the current Tag objects in the database
        foreach ($product->getTags() as $tag) {
            $originalTags->add($tag);
        }

        $editForm = $this->createForm(ProductType::class, $product);

        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() &&$editForm->isValid()) {
            $product=$editForm->getData();
            /** @var UploadedFile $file */
            $file = $product->getImgPath();
            if($file = ($file ?? null)){
                $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

                $file->move(
                    $this->getParameter('image_directory'),
                    $fileName
                );

                $product->setImgPath($fileName);
            }

            $product->setUpdateAt(time());

            foreach ($originalTags as $tag) {
                if (false === $product->getTags()->contains($tag)) {

                    $tag->getProducts()->removeElement($product);

                    $entityManager->persist($tag);

                }
            }

            $entityManager->persist($product);
            $entityManager->flush();

            return $this->redirectToRoute('list');
        }

        return $this->render('product/update.html.twig',[
            'form'=>$editForm->createView(),
        ]);
    }

    /**
     * Matches /product/ with slug
     *
     * @Route("/product/{slug}", name="product_show")
     */
    public function actionView($slug)
    {
        // $slug will equal the dynamic part of the URL
        // e.g. at /blog/yay-routing, then $slug='yay-routing'

        // ...
    }

    /*
     * Load a Product Entity by ID
     * */
    private function loadProductEntity($id){
        $repository = $this->getDoctrine()->getRepository(Product::class);
        if(($product = $repository->find($id)) !== null){
            return $product;
        }else{
            throw $this->createNotFoundException('No product found');
        }
    }

    private function generateUniqueFileName()
    {
        return md5(uniqid());
    }

    public function actionAddTag(Request $request){
        $tag= new Tag();
        $form_tag = $this->createForm(TagType::class, $tag);
        $form_tag->handleRequest($request);

        if ($form_tag->isSubmitted() && $form_tag->isValid()) {
            $tag=$form_tag->getData();
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($tag);
            $entityManager->flush();
            return $this->json(['tag'=>$tag]);
        }else
            return false;
    }
}

templates/product/_form.html.twig
{{ form_start(form) }}
<div class="form-group">
    {{ form_label(form.name,"Name") }}
    {{ form_errors(form.name) }}
    {{ form_widget(form.name,{'attr': {'class': 'form-control'}}) }}
</div>
<div class="form-group">
    {{ form_label(form.img_path,"Image") }}
    {{ form_errors(form.img_path) }}
    {{ form_widget(form.img_path) }}
</div>
<div class="form-group">
    {{ form_label(form.description) }}
    {{ form_errors(form.description) }}
    {{ form_widget(form.description,{'attr': {'class': 'form-control'}}) }}
</div>
<div class="row">
    <div class="col-xs-12">
        <div class="form-group">
            <label for="tags">Tags</label>
            <div class="tags" data-prototype="{{ form_widget(form.tags.vars.prototype)|e('html_attr') }}">
                {# iterate over each existing tag and render its only field: name #}
                {% for tag in form.tags %}
                    <div class="tags-setted">
                        {{ form_label(tag.name) }}
                        {{ form_errors(tag.name) }}
                        {{ form_widget(tag.name) }}
                    </div>
                {% endfor %}
            </div>

        </div>
    </div>
</div>
<div class="form-group">
    <div class="pull-right">
        <button type="submit" class="btn btn-primary">
            <span class="glyphicon glyphicon-floppy-disk"></span> Save it!
        </button>
    </div>
</div>
{{ form_end(form) }}

templates/product/_item_list.html.twig
<div class="col-xs-12 {{ cycle(['even', 'odd'], loop.index) }} list-table-tr list__product_item" >
    <a href="{{ path('update',{'product_id': product.id}) }}">
        <div class="col-xs-2 list-table-td">
            {{ loop.index }}
        </div>
        <div class="col-xs-2 list-table-td">
            {{ product.createAt|date("d/m/Y") }}
        </div>
        <div class="col-xs-2 list-table-td">
            {% if product.imgPath == null %}
                <i>No image</i>
            {% else %}
                <img src="{{ asset('uploads/images/' ~ product.imgPath) }}" class="img-responsive image-thumb">
            {% endif %}
        </div>
        <div class="col-xs-2 list-table-td">
            {{ product.name }}
        </div>
        <div class="col-xs-2">
            {% for tag in product.tags %}
                {{ tag.name }}
            {% endfor %}
        </div>
    </a>
</div>

templates/product/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Create product
{% endblock %}
{% block javascripts_top %}
    {{ parent() }}
{% endblock %}
{% block body %}
    <h1>Create new product</h1>
    <hr>
        <a href="{{ path('product') }}" class="btn btn-default" >Back</a>
    <hr>
    <div class="col-xs-12">
        {{ include('product/_form.html.twig', { 'form': form }) }}
    </div>

{% endblock %}
{% block javascripts_bottom %}
    {{ parent() }}
    <script src="{{ asset('js/tag_script.js') }}"></script>
{% endblock %}

templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Product page index!
{% endblock %}

{% block body %}
    <section class="dashboard-content">
        <p class="lead">Howdy!</p>
        <p class="lead"> What do you want to do today?</p>
    </section>
    <div class="row">
        <div class="col-xs-12">
            <div class="bs-glyphicons">
                <ul class="bs-glyphicons-list">
                    <a href="{{ path("list") }}">
                        <li>
                            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                            <span class="glyphicon-class">Show me <br> a list of product</span>
                        </li>
                    </a>
                    <a href="">
                        <a href="{{ path("create") }}">
                            <li >
                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                                <span class="glyphicon-class">Create <br> a new product</span>
                            </li>
                        </a>
                    </a>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

templates/product/list.html.twig
{% extends 'base.html.twig' %}

{% block javascripts_top %}
    {{ parent() }}
    <script src="{{ asset('js/jQuery.paginate.min.js') }}"></script>
{% endblock %}

{% block title %}
    Product list
{% endblock %}

{% block body %}
    <h1>Product list</h1>
    <hr>
    <div class="row">
        <div class="col-xs-12">
            <div class="pull-left">
                <a href="{{ path('product') }}" class="btn btn-default">Back</a>
            </div>
        </div>
    </div>
    <hr>
    <div class="col-xs-12">
        <div class="panel panel-default">
            <div class="panel-heading">Product inserted</div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-xs-4 pull-right">
                        <span>Filter:</span>
                        <input type="text" class="form-control" id="search" placeholder="filter...">
                    </div>

                </div>
                <div class="row mytable">
                    <div class="col-xs-12">
                        <div class="col-xs-2 list-table-th">
                            <strong>N°</strong>
                        </div>
                        <div class="col-xs-2 list-table-th">
                            <strong>Date</strong>
                        </div>
                        <div class="col-xs-2 list-table-th">
                            <strong>Image</strong>
                        </div>
                        <div class="col-xs-2 list-table-th">
                            <strong>Name</strong>
                        </div>
                        <div class="col-xs-2 list-table-th">
                            <strong>Tags</strong>
                        </div>
                    </div>
                    <div id="pagination__list_product">
                    {% for product in products %}
                        {{ include('product/_item_list.html.twig', { 'product': product,'loop':loop }) }}
                    {% else %}
                        <div class="col-xs-12">
                            <p class="text-center"><i>No product found</i></p>
                        </div>
                    {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block javascripts_bottom %}
    {{ parent() }}
    <script src="{{ asset('js/pagination_list.js') }}"></script>
{% endblock %}

templates/product/update.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Update product
{% endblock %}
{% block javascripts_top %}
    {{ parent() }}
{% endblock %}
{% block body %}
    <h1>Update product</h1>
    <hr>
    <a href="{{ path('product') }}" class="btn btn-default" >Back</a>
    <hr>
    <div class="col-xs-12">
        {{ include('product/_form.html.twig', { 'form': form }) }}
    </div>

{% endblock %}
{% block javascripts_bottom %}
    {{ parent() }}
    <script src="{{ asset('js/tag_script.js') }}"></script>
{% endblock %}

templates/product/view.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Product page index!
{% endblock %}

{% block body %}
    <section class="dashboard-content">
        <p class="lead">Howdy!</p>
        <p class="lead"> What do you want to do today?</p>
    </section>
    <div class="row">
        <div class="col-xs-12">
            <div class="bs-glyphicons">
                <ul class="bs-glyphicons-list">
                    <a href="{{ path("product_list") }}">
                        <li>
                            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                            <span class="glyphicon-class">Show me <br> a list of product</span>
                        </li>
                    </a>
                    <a href="">
                        <li>
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                            <span class="glyphicon-class">Create <br> a new product</span>
                        </li>
                    </a>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}